### ISSUE TITLE
Suggestion: Use `@context`-like objects for mapping inside front-end code

### ISSUE THREAD

**Issue by joepio** [fletcher91/link-redux#12]
When developing apps using `link-redux`, I tend to write a lot of explicit references to RDFS Classe URIs and RDFS Property URIs. These are error-prone and cumbersome to type.

Although `LRS.namespaces` helps a little with mapping ontologies, it is not optimal and unfamiliar to devs:

``` js
// In your LRS
LRS.namespaces.schema = Namespace("http://schema.org/");

// Inside your component
import { NS } from "../LRS"
<Property label={NS.schema("location")} />
```

I suggest using JSON-LD `@context` and enable ORM-like syntax, similar to [LDFlex] (https://github.com/RubenVerborgh/LDflex). Perhaps it's easier to just use .js files, so IDE's could do things like autocomplete / auto-import.

```js
// In your context.js
export default {
    schema: "http://schema.org",
    location: { "@id": "schema:location", "@type": "@id"}
}

// In your component
import { location } from "../context"
<Property label={location} />
```

**Comment by fletcher91** [comment]
It's already possible to just type `NS.schema.location` for [closed vocabularies](https://github.com/fletcher91/link-lib/blob/master/src/utilities/constants.ts#L18), which is a plain object so it supports spreading. So adding the (very verbose) JSON-LD specific format is superfluous.

**Comment by joepio** [comment]
How about this?

```jsx
import React, { useState } from 'react';
import { useLD } from 'react-ld';
import foafContext from '@context/foaf';

function Example() {
  const {
    fullName,
    email,
  } = useLD("https://example.com/rdfperson", foafContext);

  return (
    <div>
      <h1>{name}</h1>
      <a href={`mailto:${email}`}>{email}</a>
    </div>
  );
}
```

**Comment by fletcher91** [comment]
This is already possible with the [link HOC](https://fletcher91.github.io/link-redux/globals.html#link) given the component is nested within the proper LinkedResourceContainer.

```
import { link } from 'link-redux';
import React from 'react';

const foaf = {
  fullName: NS.foaf('name'),
  email: NS.foaf('mbox')
};

const Example = ({ fullName, email }) => (
  <div>
    <h1>{name}</h1>
    <a href={`mailto:${email}`}>{email}</a>
  </div>
);

export default link(context, { returnType: 'value' })(Example)
```

Or, with automatic mounting by the LRC;

```
import { link } from 'link-redux';
import React from 'react';

const foaf = {
  fullName: NS.foaf('name'),
  email: NS.foaf('mbox')
};

const Example = ({ fullName, email }) => (
  <div>
    <h1>{name}</h1>
    <a href={`mailto:${email}`}>{email}</a>
  </div>
);

Example.type = NS.foaf('Person')
Example.mapDataToProps = foaf

export default register(Example)
```

A hook for the mapDataToProps functionality is already on the planning, though that won't let you set a specific url to fetch. Passing a `subject: NamedNode` prop to the mounted container will yield the same results however;

```
const Example = () => {
  const { fullName, email } = useData(foafContext, { returnType: 'value' });

  return (
    <div>
      <h1>{name}</h1>
      <a href={`mailto:${email}`}>{email}</a>
    </div>
  );
}

// Without LRC somewhere:
<Example subject={new NamedNode("http://example.com/person/1")}>
// or with an IRI helper
<Example subject={NS.app("person/1")}>
// Or with full API usage
<LinkedResourceContainer subject={NS.app("person/1")} />
```
