### ISSUE TITLE
Use the values of multiple props in a single component

### ISSUE THREAD

**Issue by joepio** [fletcher91/link-redux#6]
Some view components are dependent on the values of various properties. I suggest adding a wrapper function similar to the redux connect function (connectLink(), perhaps?), where a set of properties for a certain resources could be fetched which are in turn passed to the wrapped component.

A possible downside to this suggestion is that it might stimulate lazy development. Properties lose relevant metadata and awareness of what they represent. They are no longer responsible for their own render function.

However, it would greatly improve the workflow for Link developers and it enables more complex composite components.

**Comment by fletcher91** [comment]
This introduces a couple of complexities which make the design and implementation not so straightforward.

First of all, it diminishes composability by restricting multiple properties into one view. Should the component be rendered if the server didn't provide all the properties asked by the component? What if a component has been registered for a superclass for which all properties are available, but a view for the most specific class misses some properties?

The option of nesting `Property` components is also available (though not very pretty), where the props are collected through the nested objects via custom props. Alternatively, the component can extend from `PropertyBase` and just use `getLinkedObjectProperty`

**Comment by fletcher91** [comment]
See https://github.com/fletcher91/link-redux/issues/7#issuecomment-404518380
